Add HTTP-API support
rawandahmad698/PyChatGPT pull request #17
Opened 2022-12-06 11:58 UTC by reycn

**Changes:**
[x] Add HTTP-API support, with a simple format notice;
[x] Updated `requirements.txt`: `fastapi` added.
[x] Updated `READ.ME`: HTTP-API tutorial, including how to install `uvicron`.
[x] Local & remote nginx reverse-proxy test passed.

**e.g.**
```
IN: 
http(s)://host:port/how%20are%20you

OUT:
"I'm a machine learning model trained by OpenAI, so I don't have feelings or emotions like a human does. I'm designed to provide answers to questions to the best of my ability based on the information I've been trained on. Is there something specific you would like to know?”
```

**On login&captcha**: 
Directly use the session token stored by cli and currently no expiration test implemented. This is because, if the token was expired, run the main cli would be enough.

2022-12-06 12:06 UTC, rawandahmad698 requested changes

2022-12-06 12:06 UTC, rawandahmad698 commented on webapi.py
> +    print(result)
And remove this

2022-12-06 13:46 UTC, reycn commented
Sure, working on it.

2022-12-06 13:47 UTC, rawandahmad698 commented
Thank you.

2022-12-06 14:27 UTC, reycn commented
- Functions, variables renamed;
- Exceptions raised as ValueError;
- Error msgs changed as instructed.

2022-12-06 14:30 UTC, rawandahmad698 commented
Looking good, will merge after tests

2022-12-06 18:07 UTC, daymanvt commented
Appreciate you guys working on this.  Maybe in a few hours of using chatgpt, I can even start helping :)

2022-12-07 09:17 UTC, reycn commented
A kindly notice: some special characters might hamper the simple solution, use post instead to solve the problem.

I will add this to a new version in few days. Currently busy for some personal issues. :0

2022-12-07 11:00 UTC, rawandahmad698 commented
Sorry for the delay, Since I released v1.0.2, this code would be conflicting, could you integrate it with the new library?

2022-12-07 15:26 UTC, reycn commented
> Sorry for the delay, Since I released v1.0.2, this code would be conflicting, could you integrate it with the new library?

OK but I need one or two days since busy for some important issues.

2022-12-09 05:28 UTC, closed without merging